export default {
    P_ADD_TO_SHELF: 'P_ADD_TO_SHELF',
    P_REMOVE_TO_SHELF: 'P_REMOVE_TO_SHELF',

    G_REQUEST_START: 'G_REQUEST_START',
    G_REQUEST_COMPLETED: 'G_REQUEST_COMPLETED',

    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT: 'LOGOUT',

}